import numpy as np
import plotly.express as px

# Bảng màu nhất quán toàn ứng dụng
SEQ = px.colors.qualitative.Set2

# Định nghĩa từ điển dịch thuật
SECTOR_VI = {
    "Agriculture-Forestry-Fishery": "Nông-Lâm-Thủy sản",
    "Manufacturing": "CN chế biến chế tạo",
    "Construction": "Xây dựng",
    "Mining": "Khai khoáng",
    "Wholesale-Retail": "Bán buôn - Bán lẻ",
    "Finance-Banking-Insurance": "Tài chính - Ngân hàng",
    "Logistics-Transport-Warehousing": "Logistics - Vận tải",
    "Information-Communication-IT": "CNTT - Truyền thông",
    "Education-Training": "Giáo dục - Đào tạo",
    "Healthcare": "Y tế",
}

REGION_VI = {
    "Northern Midlands and Mountains": "Trung du & Miền núi Bắc",
    "Red River Delta": "Đồng bằng sông Hồng",
    "North Central and South Central Coast": "Bắc TB & DH Trung Bộ",
    "Central Highlands": "Tây Nguyên",
    "Southeast": "Đông Nam Bộ",
    "Mekong Delta": "Đồng bằng sông Cửu Long",
}

# Chuỗi số liệu đầu vào cố định
K_SERIES = np.array([16500, 17800, 19600, 21300, 23500, 25900], dtype=float)
L_SERIES = np.array([53.6, 50.5, 51.7, 52.4, 52.9, 53.4], dtype=float)
D_SERIES = np.array([12.0, 12.7, 14.3, 16.5, 18.3, 19.5], dtype=float)
AI_SERIES = np.array([55.6, 60.2, 65.4, 67.0, 73.8, 80.1], dtype=float)
H_SERIES = np.array([24.1, 26.1, 26.2, 27.0, 28.4, 29.2], dtype=float)

# Hệ số co dãn hàm sản xuất
ALPHA, BETA, GAMMA, DELTA, THETA = 0.33, 0.42, 0.10, 0.08, 0.07

# Kho dữ liệu câu hỏi phản biện chính sách công
POLICY_QA = {
    1: [
        ("a", "TFP của Việt Nam có xu hướng tăng hay giảm trong giai đoạn 2020-2025? Điều đó nói lên gì về chất lượng tăng trưởng?", "TFP có xu hướng tăng. Điều này minh chứng cho việc chất lượng tăng trưởng của Việt Nam đang được cải thiện. Nền kinh tế đã giảm dần sự phụ thuộc vào mô hình phát triển theo chiều rộng (chỉ bòn rút sức lao động giá rẻ hoặc bơm vốn đầu tư ồ ạt) và chuyển dịch sang mô hình phát triển theo chiều sâu, dựa trên đổi mới sáng tạo, tối ưu hóa quy trình và khả năng ứng dụng công nghệ."),
        ("b", "Trong các yếu tố mới D, AI, H, yếu tố nào đóng góp nhiều nhất cho tăng trưởng giai đoạn vừa qua? Vì sao?", "Yếu tố Số hóa (D) đóng góp nhiều nhất (chiếm 13.91% theo đồ thị). Lý do là giai đoạn 2020-2025 (đặc biệt sau cú hích COVID-19), hạ tầng thanh toán điện tử, thương mại điện tử và dịch vụ công trực tuyến của Việt Nam bùng nổ mạnh mẽ. Chỉ số kinh tế số/GDP tăng nhanh từ 12% (2020) lên 19.5% (2025), mang lại tác động ngay lập tức tới năng suất thương mại."),
        ("c", "Mục tiêu Việt Nam đạt 30% kinh tế số/GDP vào 2030 có khả thi không nếu dựa trên mô hình này? Cần ràng buộc gì?", "Rất khả thi về mặt toán học. Tuy nhiên, để đạt được con số này trong thực tiễn, chính sách cần sự ràng buộc chặt chẽ và đồng bộ từ các yếu tố bổ trợ:\nRàng buộc về nguồn nhân lực (H): Phải đạt tối thiểu 35% lao động qua đào tạo như kịch bản mô phỏng, vì nếu không có nhân sự vận hành thì hạ tầng số chỉ là \"cái xác không hồn\".\nRàng buộc về doanh nghiệp công nghệ (AI): Cần đạt quy mô 100 nghìn doanh nghiệp số để làm lực lượng nòng cốt chuyển giao công nghệ cho các khối ngành truyền thống. Cơ cấu đầu tư phải hài hòa, không được phép \"lệch pha\" bỏ rơi giáo dục và R&D."),
    ],
    2: [
        ("a", "Ý nghĩa của Shadow Price (Giá đối ngẫu) và Chi phí cơ hội?", "Shadow Price chạy ra ở bài này là 1.35. Nghĩa là: Nếu Chính phủ tăng thêm 1 tỷ VND vào tổng ngân sách 100.000 tỷ này, GDP kỳ vọng sẽ tăng thêm chính xác 1.35 tỷ VND.\nĐây hoàn toàn có thể coi là cận trên hợp lý của chi phí cơ hội. Nếu Chính phủ định mang 1 tỷ đó đi xây cầu đường mà GDP sinh ra nhỏ hơn 1.35 tỷ, thì đầu tư vào số hóa đang sinh lời tốt hơn. (Lý do hàm tăng thêm 1.35 là vì bộ tối ưu sẽ tự động ném 1 tỷ dôi dư đó vào $x_4$ - R&D, vì R&D có hệ số sinh lời cao nhất là 1.35) ."),
        ("b", "Vì sao R&D có hệ số tác động cao nhất nhưng lại có ràng buộc tối thiểu thấp nhất (10 nghìn tỷ)?", "Trong kinh tế vĩ mô, đầu tư R&D mang tính chất \"High risk, high return\" và có độ trễ rất dài. Việc đặt mức sàn thấp (10 nghìn tỷ) phản ánh sự thận trọng của nhà nước: bảo vệ ngân sách khỏi rủi ro thất bại của các dự án R&D trong ngắn hạn, đồng thời ưu tiên vốn cho các nền tảng bức thiết hơn (như Hạ tầng số và Nhân lực) để giải quyết bài toán trước mắt."),
        ("c", "Tỷ lệ 35% công nghệ chiến lược (AI+R&D) có khả thi không?", "Về mặt mô hình thì tỷ lệ này hoàn toàn chạy ra nghiệm tối ưu. Tuy nhiên, trong thực tiễn điều hành ngân sách Việt Nam 2025, điều này rất khó khả thi. Ngân sách nhà nước đang bị chi phối bởi các ưu tiên cốt lõi: Hạ tầng giao thông (đường cao tốc Bắc - Nam, sân bay Long Thành) và an sinh xã hội. Đẩy 35% ngân sách số (tương đương 35.000 tỷ) vào AI và R&D sẽ tạo ra áp lực tài khóa cực lớn và có nguy cơ giải ngân chậm do thiếu hụt trầm trọng nhân sự nghiên cứu cấp cao."),
    ],
    3: [
        ("a", "Ba ngành nào nên được ưu tiên đẩy mạnh chuyển đổi số và AI trước? Có phù hợp với Nghị quyết 57-NQ/TW không?", "Nhìn vào kết quả mặc định, Top 3 thường sẽ gọi tên CNTT-Truyền thông (IT), Công nghiệp chế biến chế tạo và Tài chính - Ngân hàng. Điều này hoàn toàn khớp với định hướng của Nghị quyết 57-NQ/TW về việc chọn các ngành có sức lan tỏa lớn, sẵn sàng về mặt dữ liệu và hạ tầng để làm mũi nhọn đột phá, tạo động lực kéo các ngành khác đi lên."),
        ("b", "Tại sao ngành Khai khoáng có năng suất rất cao nhưng vẫn không nằm trong nhóm ưu tiên?", "Mặc dù ngành Khai khoáng tạo ra giá trị GDP trên mỗi lao động cực kỳ cao, nhưng nó lại bị \"kéo tụt\" điểm ở các tiêu chí khác. Ngành này sử dụng rất ít lao động (chỉ 0.3 triệu, xếp chót về tác động việc làm), hệ số lan tỏa sang các ngành khác thấp (0.30) , mức độ sẵn sàng AI kém (30) và rủi ro tự động hóa thay thế việc làm lại rất cao (55%). Đầu tư chuyển đổi số vào đây sinh lời về mặt tài chính nhưng tạo ra ít giá trị thặng dư xã hội."),
        ("c", "Bộ trọng số nên do ai quyết định: chuyên gia kỹ thuật, hội đồng chính sách, hay quy trình đối thoại công khai?", "Từ góc độ quản trị công, việc quyết định bộ trọng số không bao giờ là bài toán thuần túy kỹ thuật. Chuyên gia kỹ thuật chỉ có thể cung cấp mô hình (như chúng ta vừa code) và phân tích độ nhạy. Bộ trọng số cuối cùng phải được quyết định bởi Hội đồng chính sách thông qua đối thoại công khai với các bên liên quan (doanh nghiệp, hiệp hội lao động). Lý do là mỗi một con số phần trăm thay đổi trong trọng số sẽ làm thay đổi dòng vốn hàng chục nghìn tỷ đồng, trực tiếp ảnh hưởng đến sinh kế của hàng triệu lao động và cấu trúc nền kinh tế."),
    ],
    4: [
        ("a", "If bỏ ràng buộc công bằng, vốn sẽ chảy về vùng nào? Tại sao? Hậu quả xã hội dài hạn ra sao?", "Nếu không có ràng buộc công bằng (bỏ C5), mô hình tối ưu sẽ \"ích kỷ\" dồn tối đa tiền vào Đồng bằng sông Hồng (RRD) và Đông Nam Bộ (SE) cho mảng Số hóa (D) và AI vì hệ số biên $\\beta$ ở đây cực kỳ cao (ví dụ AI ở SE lên tới 1.55). Các vùng khó khăn như Tây Nguyên (CH) hay Miền núi phía Bắc (NMM) sẽ chỉ nhận mức sàn 5.000 tỷ để chống đối.\n\n_Hậu quả:_  Điều này tạo ra Vùng trũng số (Digital Divide). Những vùng giàu công nghệ sẽ càng thu hút chất xám và đầu tư FDI, trong khi vùng nghèo bị bỏ lại phía sau, gây mất cân bằng xã hội và chênh lệch giàu nghèo nghiêm trọng trong dài hạn."),
        ("b", "Ràng buộc trần ngân sách mỗi vùng (C3) có thể coi như một \"chính sách phân quyền\". Mức giảm $Z^*$ này có chấp nhận được không?", "Việc áp trần 12.000 tỷ/vùng (C3) buộc dòng vốn phải phân tán ra các địa phương khác, làm giảm tổng GDP kỳ vọng (thể hiện qua chênh lệch $Z^*$ giữa hai mô hình). Tuy nhiên, mức suy giảm này hoàn toàn chấp nhận được vì nó đổi lại tính ổn định vĩ mô, trao quyền tự quyết cho địa phương và tạo ra các cực tăng trưởng vệ tinh thay vì chỉ phụ thuộc vào Hà Nội và TP.HCM."),
        ("c", "Vùng Tây Nguyên (CH) có sàn 5.000 tỷ nhưng hệ số AI rất thấp (0,45). Nên đầu tư AI tại Tây Nguyên hay tập trung H và I trước?", "Mô hình đã trả lời rất rõ ràng (hãy nhìn vào Heatmap): Dòng tiền phân bổ cho AI tại Tây Nguyên gần như bằng 0 (hoặc ở mức tối thiểu). Hệ số AI thấp (0,45) phản ánh năng lực hấp thụ công nghệ yếu. Thay vào đó, mô hình dồn vốn của Tây Nguyên vào Nhân lực số (H - 1.35) và Hạ tầng số (I - 1.20). Khuyến nghị chính sách là: Ở Tây Nguyên, phải xây dựng nền tảng viễn thông và con người trước khi mộng mơ về Trí tuệ nhân tạo."),
    ],
    5: [
        ("a", "Vì sao mô hình bỏ qua dự án P15 (Open Data) dù tỷ suất lợi ích/chi phí rất cao? Đây có phải là kết quả mong muốn không?", "Dự án P15 có chi phí rất rẻ (1.500 tỷ) và mang lại NPV 3.800 tỷ (tỷ suất sinh lời $> 2.5$ lần). Tuy nhiên, mô hình đã nhẫn tâm gạch bỏ nó. Lý do cốt lõi nằm ở ràng buộc C7: \"Tối đa 11 dự án\". Để tối đa hóa lợi ích tuyệt đối ($Z^*$), thuật toán ưu tiên nhét các dự án \"hạng nặng\" (chi phí cao, lợi ích tuyệt đối khổng lồ) để lấp đầy 11 vị trí.\nVề mặt chính sách, đây là kết quả không mong muốn. Các dự án dữ liệu mở tuy nhỏ nhưng tạo ra hệ sinh thái nền tảng cho startup. Việc áp đặt một con số lượng dự án tối đa cứng nhắc đã bóp nghẹt các sáng kiến giá rẻ, hiệu quả cao."),
        ("b", "Ràng buộc \"bắt buộc P14 (an ninh mạng)\" có làm giảm $Z^*$ không? Việc bắt buộc này có hợp lý không?", "Chắc chắn làm giảm $Z^*$ (chi phí cơ hội). Nếu thả rông, thuật toán có thể dùng 3.800 tỷ của P14 để dồn vào dự án khác sinh lời cao hơn mức 7.500 tỷ của nó. Tuy nhiên, việc ép buộc này là cực kỳ hợp lý. An ninh mạng (SOC) là hàng hóa công cộng (public good). Lợi ích của nó không nằm ở NPV tài chính, mà nằm ở việc chặn đứng nguy cơ sụp đổ của toàn bộ 14 dự án còn lại nếu bị tấn công mạng."),
        ("c", "Mô hình giả định các dự án độc lập, nhưng thực tế P8 (AI) và P13 (Bán dẫn) có lợi ích cộng hưởng. Làm thế nào để mô hình hóa?", "Để mô hình hóa hiệu ứng cộng hưởng trong quy hoạch tuyến tính nguyên (MIP), ta cần đưa thêm một \"biến phụ\" nhị phân, gọi là $y_{8\\_13}$. Biến này chỉ bằng 1 khi cả $y_8$ và $y_{13}$ đều bằng 1.\n\n_Toán học:_  $y_{8\\_13} \\le y_8$, $y_{8\\_13} \\le y_{13}$, và $y_{8\\_13} \\ge y_8 + y_{13} - 1$.\nSau đó, cộng thêm một khoản lợi ích gia tăng ($B_{bonus} \\cdot y_{8\\_13}$) vào hàm mục tiêu $Z$."),
    ],
    6: [
        ("a", "Vùng nào dẫn đầu theo TOPSIS với trọng số chuyên gia? Có nên triển khai trung tâm AI đầu tiên không?", "Theo trọng số chuyên gia, Đông Nam Bộ (Southeast) và Đồng bằng sông Hồng (Red River Delta) thống trị bảng xếp hạng do sở hữu điểm số áp đảo về năng lực số, FDI và tỷ lệ lao động qua đào tạo. Đây chắc chắn là hai khu vực đầu tiên phải đặt trung tâm AI quốc gia để tận dụng cơ sở hạ tầng có sẵn và tối đa hóa hiệu ứng lan tỏa, phù hợp với tầm nhìn biến Việt Nam thành trung tâm AI của ASEAN."),
        ("b", "Khi dùng trọng số Entropy, vùng nào có sự thay đổi xếp hạng lớn nhất? Vì sao?", "Phương pháp Entropy gán trọng số cao cho những tiêu chí có độ phân tán (phương sai) lớn giữa các phương án, và triệt tiêu các tiêu chí có giá trị na ná nhau. Chỉ số Gini của 6 vùng đều xoay quanh mức 0.35 - 0.41 (độ lệch rất nhỏ), nên Entropy gần như gạch bỏ tiêu chí công bằng xã hội này. Ngược lại, FDI có sự chênh lệch khủng khiếp (Đông Nam Bộ 18.5 tỷ USD so với Tây Nguyên 0.8 tỷ USD) nên sẽ được Entropy buff trọng số lên cực cao. Tuy nhiên trên dữ liệu thực, dịch chuyển hạng chỉ ở mức ±1 bậc (Đông Nam Bộ ↔ ĐB sông Hồng hoán đổi Top-1/Top-2; ĐB sông Cửu Long tụt từ hạng 4 xuống 5) — nhóm dẫn đầu vẫn ổn định, kết quả bền vững giữa hai cách gán trọng số."),
        ("c", "TOPSIS giả định các tiêu chí độc lập tuyến tính. Nhưng AI Readiness và Internet tương quan rất cao. Ảnh hưởng thế nào và cách xử lý?", "Khi hai tiêu chí tương quan quá chặt, việc dùng cả hai trong TOPSIS sẽ dẫn đến hiện tượng đếm kép (double counting), làm thổi phồng điểm số của các vùng vốn đã mạnh về viễn thông. Cách xử lý chuyên nghiệp nhất về mặt dữ liệu là chạy thuật toán Giảm chiều dữ liệu (PCA - Principal Component Analysis) trước để gộp các biến tương quan lại, hoặc thay thế khoảng cách Euclide thông thường bằng khoảng cách Mahalanobis (khoảng cách có hiệp phương sai)."),
        ("d", "Chọn 3 vùng nào để xây 3 trung tâm AI theo Quyết định 127/QĐ-TTg? Có cần xét địa-chính trị không?", "If xét rập khuôn theo TOPSIS, 3 trung tâm sẽ rơi hết vào Đông Nam Bộ, Đồng bằng sông Hồng và có thể là Bắc Trung Bộ + Duyên hải miền Trung. Tuy nhiên, trong quy hoạch công (Public Governance), tiêu chí địa - chính trị là bắt buộc. Để đảm bảo an ninh dữ liệu quốc gia (phân tán rủi ro thiên tai) và công bằng phát triển, 3 trung tâm nên được đặt theo thế \"kiềng 3 chân\": Miền Bắc (Hòa Lạc, Hà Nội), Miền Trung (Đà Nẵng) và Miền Nam (TP.HCM hoặc Bình Dương). Thuật toán chỉ hỗ trợ ra quyết định, không thay thế được trách nhiệm chính trị của con người."),
    ],
    7: [
        ("a", "Khi quan sát đường biên Pareto, em thấy đánh đổi giữa tăng trưởng và bao trùm có rõ ràng không? Mức đánh đổi đó nói lên điều gì về cơ cấu kinh tế Việt Nam?", "Khi quan sát không gian nghiệm trên đường biên Pareto, sự đánh đổi giữa mục tiêu tăng trưởng ($f_1$ - GDP Gain) và bao trùm ($f_2$ - Giảm bất bình đẳng) thể hiện cực kỳ rõ ràng và khốc liệt. Để đạt được mức GDP tối đa, hệ thống bắt buộc phải chấp nhận chỉ số bất bình đẳng vùng miền (MAD) tăng vọt.Mức đánh đổi này phản ánh thực trạng cơ cấu kinh tế \"kép\" và phát triển không đồng đều của Việt Nam. Năng lực hấp thụ công nghệ số, hạ tầng lõi và chất lượng nhân lực hiện nay tập trung áp đảo ở hai đầu tàu là Đồng bằng sông Hồng và Đông Nam Bộ. Nếu chỉ tối ưu hóa lợi ích kinh tế thuần túy, dòng vốn sẽ tự động tuân theo quy luật thị trường chảy về các \"rốn\" công nghệ này để sinh lời nhanh nhất, bỏ lại các vùng ngoại biên (Tây Nguyên, Trung du miền núi phía Bắc) và khoét sâu thêm hố ngăn cách số (Digital Divide)."),
        ("b", "Trọng số (0,40; 0,25; 0,20; 0,15) có phản ánh đúng ưu tiên hiện tại của Việt Nam (theo các văn kiện Đại hội XIII) không? Em sẽ điều chỉnh thế nào để phù hợp với cam kết COP26 và Quyết định 127/QĐ-TTg?", "Bộ trọng số hiện tại (ưu tiên tới 40% cho GDP) mang đậm tư duy của giai đoạn phát triển trước đây, nhưng chưa phản ánh hoàn toàn chính xác tinh thần của Đại hội XIII. Văn kiện Đại hội XIII nhấn mạnh định hướng \"phát triển nhanh nhưng phải bền vững và bao trùm\".Để phù hợp với cam kết COP26 (đạt phát thải ròng bằng \"0\" vào năm 2050) và Quyết định 127/QĐ-TTg (Chiến lược quốc gia về AI nhấn mạnh phát triển AI an toàn, có trách nhiệm), em sẽ điều chỉnh giảm trọng số GDP và tăng trọng số cho các mục tiêu còn lại. \n\n_Cụ thể:_ Tăng trưởng GDP ($f_1$): Giảm xuống 0,30 (Chấp nhận giảm tốc độ để đổi lấy chất lượng).Môi trường ($f_3$): Tăng lên 0,30 (Thể hiện cam kết mạnh mẽ, ép buộc các dự án công nghệ phải sử dụng năng lượng xanh, trung hòa carbon).Công bằng bao trùm ($f_2$): Giữ ở mức 0,25.Rủi ro an ninh ($f_4$): Tăng lên 0,15 (Dành nguồn lực để xây dựng rào chắn an toàn AI quốc gia)."),
        ("c", "Vai trò của NSGA-II ở đây có gì khác so với LP đơn mục tiêu? Nó có thay thế được quyết định chính trị không?", "Sự khác biệt cốt lõi nằm ở đầu ra. Quy hoạch tuyến tính (LP) đơn mục tiêu hoạt động như một cỗ máy cứng nhắc, chỉ nhả ra một đáp án duy nhất (tối ưu tuyệt đối một biến và phớt lờ các hệ lụy xung quanh). Ngược lại, NSGA-II cung cấp một đường biên Pareto (menu các phương án thỏa hiệp), cho phép nhà quản lý nhìn thấy rõ bức tranh toàn cảnh: Muốn được thêm A thì phải hy sinh bao nhiêu B.Tuy nhiên, NSGA-II (hay bất kỳ thuật toán AI nào) hoàn toàn không thể thay thế được quyết định chính trị. Thuật toán chỉ đóng vai trò \"cố vấn kỹ thuật\" để lượng hóa các kịch bản. Việc quyết định chọn điểm rơi nào trên đường biên Pareto, sẵn sàng đánh đổi bao nhiêu phần trăm GDP để lấy sự công bằng cho người nghèo hay bảo vệ môi trường, là lăng kính giá trị đòi hỏi ý chí chính trị, sự đồng thuận xã hội và tầm nhìn của con người."),
    ],
    8: [
        ("a", "Quỹ đạo tối ưu của K, D, AI, H có “front-loaded” hay “back-loaded” không? Vì sao mô hình đề xuất như vậy?", "Kết quả chạy mô hình tối ưu động cho thấy quỹ đạo phân bổ có xu hướng \"front-loaded\" (dồn vốn mạnh vào đầu kỳ), đặc biệt là đối với các loại vốn công nghệ (D và AI). Đầu tư đạt đỉnh ở các năm đầu tiên và có xu hướng giảm dần hoặc đi ngang ở cuối chu kỳ. Thuật toán tối ưu hóa tổng giá trị hiện tại (NPV) của GDP. Việc dồn vốn (front-load) giúp nền kinh tế tích lũy tư bản ($K, D, AI, H$) và đẩy năng suất tổng hợp (TFP) lên cao từ rất sớm. Nhờ có quy mô tư bản lớn ngay từ đầu, hệ thống sẽ sinh ra mức GDP cao hơn trong suốt chuỗi 10 năm sau đó nhờ \"hiệu ứng lãi kép\". Nếu làm ngược lại (back-loaded), công nghệ được đầu tư ở cuối kỳ chưa kịp phát huy tác dụng lan tỏa thì thời gian quy hoạch đã kết thúc, làm giảm tổng lợi ích vĩ mô."),
        ("b", "Tỷ lệ đầu tư AI/đầu tư H theo thời gian có ổn định không? Mô hình ngụ ý gì về việc đào tạo nhân lực nên đi trước hay đồng thời với đầu tư AI?", "Tỷ lệ đầu tư AI/H không hề ổn định mà có sự chuyển dịch động qua các năm. Ban đầu, mô hình dồn lực rất mạnh cho H, sau đó tỷ trọng AI mới dần tăng lên hoặc duy trì song song. Mô hình ngụ ý rõ ràng rằng: Đào tạo nhân lực (H) bắt buộc phải đi trước một nhịp, hoặc ít nhất là đồng thời cường độ cao ngay từ vạch xuất phát cùng với AI. Xét về mặt hệ số hàm sản xuất, vốn nhân lực ($H$) có tính chất tích lũy chậm nhưng tỷ lệ khấu hao lại rất thấp ($\\delta_H = 2\\%$). Ngược lại, công nghệ AI có chu kỳ lỗi thời cực nhanh ($\\delta_{AI} = 20\\%$). Nếu Chính phủ ồ ạt mua sắm thiết bị AI mà không có đội ngũ nhân sự số đi trước để vận hành, lượng AI đó sẽ nhanh chóng bị khấu hao, đắp chiếu và lãng phí mà không tạo ra GDP. Do đó, thuật toán thông minh sẽ tự động ưu tiên gieo mầm Nhân lực trước để tạo \"hạ tầng mềm\" hấp thụ công nghệ sau này."),
        ("c", "Hệ số chiết khấu ρ = 0,97 ngụ ý chính phủ quan tâm nhiều đến dài hạn. Nếu ρ = 0,90 (ngắn hạn hơn), kết quả thay đổi thế nào? Đây có phải lý do các chính phủ thường “dưới đầu tư” vào R&D?", "If giảm hệ số chiết khấu xuống $\\rho = 0,90$ (tức là tăng tỷ lệ chiết khấu $r$ lên rất cao), quỹ đạo tối ưu sẽ bị bẻ gãy: Thuật toán lập tức cắt giảm mạnh dòng vốn dành cho R&D, AI và Số hóa, chuyển sang ưu tiên dồn tiền cho Hạ tầng cứng ($K$) để vắt ra GDP ngắn hạn. Hệ số $\\rho$ thấp thể hiện sự \"sốt ruột\", định giá dòng tiền tương lai cực kỳ rẻ mạt và chỉ quan tâm đến lợi ích trước mắt. R&D và AI đòi hỏi chi phí chìm rất lớn ở hiện tại, nhưng thành quả kinh tế chỉ nở rộ ở tương lai xa (5-10 năm sau). Khi tương lai bị đánh giá thấp, mô hình toán học sẽ cho rằng đầu tư công nghệ là \"không đáng\".Đây chính xác là lời giải thích kinh điển trong kinh tế học chính trị cho căn bệnh \"Dưới đầu tư (Underinvestment)\" vào R&D: Các chính phủ có \"tư duy nhiệm kỳ\" (ngắn hạn, $\\rho$ thấp) sẽ luôn ưu tiên giải ngân vào cầu cống, đường sá để lấy thành tích GDP ngay trong nhiệm kỳ của mình, thay vì gieo mầm công nghệ cao cho thế hệ lãnh đạo tiếp theo hưởng lợi."),
    ],
    9: [
        ("a", "Ngành nào cần đầu tư đào tạo lại nhiều nhất theo kết quả tối ưu? Có khớp với cảm nhận thực tế ở Việt Nam không?", "Theo logic của thuật toán tối ưu (ràng buộc C3: $Displaced \\le Retrain$), ngành Công nghiệp Chế biến - Chế tạo (Manufacturing) và Nông - Lâm - Thủy sản là những ngành đòi hỏi dòng vốn $x_H$ (đào tạo lại) khổng lồ nhất. Lý do là hai ngành này có tổng quy mô lao động quá lớn, nên dù tỷ lệ tự động hóa nhích lên một chút cũng tạo ra con số tuyệt đối hàng triệu người mất việc, ép hệ thống phải dồn tiền đào tạo để bù đắp.\n\n_Khớp với thực tế Việt Nam:_  Điều này hoàn toàn phản ánh đúng thực trạng vĩ mô của nước ta. Nền kinh tế Việt Nam hiện đang thâm dụng lao động giá rẻ rất mạnh ở mảng gia công (Dệt may, Da giày, Lắp ráp điện tử) và nông nghiệp truyền thống. Đây chính là nhóm đối tượng dễ bị tổn thương nhất trước làn sóng AI và Robot, đòi hỏi Chính phủ phải can thiệp bằng các quỹ đào tạo nghề lớn nhất."),
        ("b", "Ngành Tài chính-Ngân hàng có nguy cơ thay thế 52% nhưng cũng có hệ số tạo việc làm mới rất cao. Mô hình khuyến nghị chiến lược gì cho ngành này?", "Với đặc thù \"Rủi ro cao - Sinh lời việc làm cũng cực cao\", thuật toán quy hoạch tuyến tính sẽ khuyến nghị chiến lược \"Tấn công song mã\" (Đẩy max cả $x_{AI}$ và $x_H$).\n\n_Phân tích chiến lược:_  Mô hình sẽ ưu tiên bơm ngân sách tối đa cho $x_{AI}$ vào ngành Tài chính để tận dụng hệ số tạo việc làm mới (Spillover) tuyệt vời của ngành này nhằm kéo tổng $Z^*$ (Việc làm ròng) lên. Đồng thời, mô hình sẽ phân bổ một lượng $x_H$ vừa đủ khít để đào tạo chuyển đổi 52% nhân sự bị đào thải (ví dụ: giao dịch viên quầy, nhập liệu) thành lực lượng phục vụ chính cho các vị trí mới (ví dụ: chuyên viên quản trị dữ liệu khách hàng, hỗ trợ ngân hàng số)."),
        ("c", "Có nên đầu tư $x_{AI}$ vào ngành Nông-Lâm-Thủy sản không, vì hệ số tạo việc làm AI thấp (8,5) nhưng số lao động dịch chuyển lại rất lớn? Mô hình nói gì?", "Mô hình toán học khuyến nghị KHÔNG HOẶC HẠN CHẾ TỐI ĐA việc đầu tư $x_{AI}$ vào ngành này.\n\n_Phân tích từ mô hình:_  Vì mục tiêu của thuật toán là Tối đa hóa Việc làm ròng ($Z^*$), nó sẽ cực kỳ e dè với Nông nghiệp. Việc bơm 1 tỷ $x_{AI}$ vào đây chỉ tạo ra hệ số việc làm mới rất thấp (8,5), nhưng lại làm hàng loạt nông dân mất việc. Để thỏa mãn ràng buộc an sinh (C3), thuật toán lại phải cắn răng rút tiền từ ngân sách để đập vào $x_H$ (đào tạo lại) cho nông dân. Quá trình này tiêu tốn rất nhiều nguồn lực $Total\\_Budget$ mà kết quả Net Job thu về gần như bằng 0 hoặc âm. Do đó, mô hình sẽ dồn vốn sang các ngành dịch vụ/công nghệ khác hiệu quả hơn."),
        ("d", "“Tốc độ tự động hóa không nên vượt quá năng lực đào tạo lại” - phát biểu này (Mục 10 của bài báo nguồn) được biểu diễn bằng ràng buộc nào trong mô hình? Em có đề xuất bổ sung ràng buộc nào để bảo đảm an sinh xã hội không?", "Phát biểu này chính là tinh thần cốt lõi của Ràng buộc C3: $Displaced \\le Retrain$ (Số lao động bị hất văng phải nhỏ hơn hoặc bằng số lao động được hệ thống đào tạo lại và tái bố trí).\n\n_Đề xuất bổ sung ràng buộc an sinh:_  Ràng buộc C3 hiện tại giả định rằng \"Cứ có tiền là sẽ đào tạo lại được tất cả\". Trong thực tế, hệ thống trường dạy nghề của Nhà nước có giới hạn về năng lực vật lý (số lượng giáo viên, cơ sở vật chất). Do đó, em đề xuất bổ sung thêm Ràng buộc Trần năng lực đào tạo (Capacity Cap):Tổng Số người được đào tạo lại (Retrain) <= Sức chứa tối đa của hệ thống giáo dục quốc gia mỗi năm (Ví dụ: 500.000 người/năm).Nếu không có ràng buộc này, mô hình có thể ảo tưởng rằng bơm tiền là cứu được ngay 5 triệu người mất việc trong 1 năm, gây sụp đổ hệ thống an sinh ngoài thực tế."),
    ],
    10: [
        ("a", "So với lời giải xác định (EV), lời giải SP có xu hướng đầu tư H nhiều hơn hay ít hơn? Vì sao?", "Mô hình ngẫu nhiên (SP) có xu hướng phân bổ vốn vào Nhân lực số ($H$) nhiều hơn đáng kể so với mô hình giải pháp xác định (EV - chỉ dựa trên trung bình).\n\n_Lý do kinh tế - toán học:_  Chìa khóa nằm ở ràng buộc $y^+_{AI} \\le 0.5 \\times x_H$ (ở Giai đoạn 2, không thể tăng cường AI vượt quá 50% quỹ nhân lực đã chuẩn bị ở Giai đoạn 1). Lời giải EV phớt lờ các kịch bản cực đoan nên chỉ đầu tư $H$ vừa đủ cho mức trung bình. Ngược lại, mô hình SP \"nhìn thấy\" trước kịch bản bùng nổ ($s4$) - nơi lợi nhuận từ AI tăng vọt gấp 1.5 lần. Để có thể dốc túi đầu tư mạnh vào AI ở kịch bản $s4$ nhằm tối đa hóa lợi nhuận, SP buộc phải đầu tư dư thừa $H$ ngay từ Giai đoạn 1 (Here-and-Now). Lúc này, $H$ đóng vai trò như một \"Quyền chọn thực\" (Real Option): Chấp nhận tốn kém duy trì $H$ ở kịch bản xấu để đổi lấy khả năng bứt tốc ngay lập tức nếu thị trường bùng nổ."),
        ("b", "VSS dương nói lên điều gì về giá trị của tư duy xác suất trong hoạch định chính sách Việt Nam?", "Chỉ số VSS (Value of Stochastic Solution) dương minh chứng bằng định lượng rằng: Việc lập kế hoạch bằng cách \"cào bằng trung bình\" rủi ro sẽ dẫn đến thiệt hại kinh tế vĩ mô.\n\n_Lý do kinh tế:_  Hoạch định chính sách ngân sách tại Việt Nam từ trước đến nay thường đi theo lối mòn Kế hoạch xác định (Deterministic Planning) - vẽ ra một kịch bản cơ sở duy nhất rồi chốt ngân sách cứng. $VSS > 0$ là lời cảnh tỉnh từ toán học: Chính phủ cần chuyển dịch sang Kế hoạch động (Stochastic Planning). Tức là phải chấp nhận một khoản chi phí dự phòng ban đầu, phân bổ ngân sách dự dật cho các nguồn lực linh hoạt (như Nhân sự), thay vì dồn hết tiền vào hạ tầng cứng chỉ để chạy theo một viễn cảnh màu hồng duy nhất."),
        ("c", "Đại dịch COVID-19 (2020-2022) và bão Yagi (2024) là các cú sốc thực tế. Bài học rút ra: liệu Việt Nam có đang “dưới đầu tư” vào nhân lực số như một hàng hóa bảo hiểm?", "Chắc chắn là CÓ. Việt Nam đang rơi vào tình trạng \"dưới đầu tư\" (under-invest) nghiêm trọng vào nhân lực số ($H$) so với sự hăng hái xây dựng hạ tầng phần cứng ($I$).\n\n_Lý do kinh tế:_  Hãy nhìn vào cú sốc $s1$ trong mô hình so với thực tế bão Yagi hay COVID-19. Khi khủng hoảng nổ ra, toàn bộ tài sản vật lý (nhà xưởng, cầu đường, cáp quang đứt gãy) lập tức bị tê liệt hoặc phá hủy, kéo theo GDP suy sụp. Ngược lại, Nhân lực số là tài sản duy nhất không bị tàn phá bởi thiên tai. Lực lượng này có khả năng chuyển đổi trạng thái linh hoạt, làm việc từ xa, và duy trì dòng chảy kinh tế số xuyên suốt khủng hoảng. Qua lăng kính của mô hình phân bổ, Nhân lực số không chỉ là chi phí đào tạo, mà phải được định giá như một \"Hàng hóa bảo hiểm\" (Strategic Buffer) vô giá giúp nền kinh tế chống chịu (resilience) trước các cú sốc cực đoan phi truyền thống."),
    ],
    11: [
        ("a", "Khi nền kinh tế ở trạng thái GDP growth thấp, D thấp, U cao - chính sách $\\pi^*(s)$ chọn hành động gì? Có khớp với “quick win” hay không?", "Trong trạng thái này, chính sách tối ưu $\\pi^*(s)$ từ mô hình Q-Learning/DQN sẽ ưu tiên chọn hành động a1 (Ưu tiên đầu tư Hạ tầng số - $D$) hoặc a0 (Phân bổ cân bằng cơ sở).\n\n_Ý nghĩa chính sách:_  Quyết định này hoàn toàn trùng khớp với chiến lược \"Quick win\" (Thắng nhanh ngắn hạn). Khi nền kinh tế đang suy thoái (GDP thấp) và hạ tầng số còn sơ khai ($D$ thấp), việc bơm tiền vào các dự án hạ tầng phần cứng (phủ sóng 5G, xây trung tâm dữ liệu, lắp cáp quang) sẽ ngay lập tức kích cầu đầu tư công, tạo ra việc làm trực tiếp cho ngành xây dựng/viễn thông, và nâng nền tảng số lên rất nhanh. Đây là bước đi dễ làm, thấy ngay kết quả để tạo đà tâm lý tốt cho thị trường trước khi tính đến các bước đi phức tạp hơn."),
        ("b", "Khi GDP growth cao, AI cao, U thấp - chính sách chọn gì? Phù hợp với “consolidation” không?", "Khi các chỉ số nền tảng đã đạt đỉnh (GDP cao, AI mạnh, Thất nghiệp $U$ thấp), chính sách $\\pi^*(s)$ sẽ chuyển dịch sang chọn hành động a3 (Ưu tiên đầu tư Nhân lực số - $H$) hoặc a2 (Tập trung tối ưu chiều sâu AI).\n\n_Ý nghĩa chính sách:_  Quyết định này hoàn toàn phù hợp với chiến lược \"Consolidation\" (Củng cố và bền vững). Khi nền kinh tế đã qua giai đoạn tăng trưởng nóng bằng phần cứng, việc tiếp tục đổ tiền vào hạ tầng sẽ gây lãng phí (khấu hao công nghệ rất nhanh). Lúc này, hệ thống cần \"hạ cánh mềm\" và tập trung vào chiều sâu: củng cố thể chế, nâng cao chất lượng nhân lực cao cấp, bảo trì hệ thống và tối ưu hóa các mô hình AI hiện có. Đây là giai đoạn chuyển từ tăng trưởng theo chiều rộng sang tăng trưởng theo chiều sâu để tạo nội lực bền vững."),
        ("c", "Mục 11 của bài báo nguồn nhấn mạnh “AI không thay thế quyết định chính trị - xã hội”. Em sẽ tích hợp $\\pi^*$ vào quy trình hoạch định chính sách Việt Nam như thế nào để không vi phạm nguyên tắc này?", "Để tích hợp mô hình học tăng cường $\\pi^*$ vào quy trình hoạch định chính sách thực tế tại Việt Nam mà không vi phạm nguyên tắc tối thượng trên, em đề xuất mô hình \"Human-in-the-loop\" (Con người kiểm soát trung tâm) theo cơ chế 3 bước:Giai đoạn Khuyến nghị (AI làm Cố vấn): Mô hình $\\pi^*$ sẽ đóng vai trò là một \"trợ lý ảo vĩ mô\" cho Bộ Kế hoạch và Đầu tư hoặc Bộ Thông tin và Truyền thông. Dựa trên dữ liệu thời gian thực, AI sẽ chạy giả lập và đưa ra bảng thực đơn các phương án đánh đổi (Trade-off Menu) kèm theo dự báo xác suất thành công.Giai đoạn Thẩm định (Hội đồng chuyên gia): Các khuyến nghị của AI (hộp đen) buộc phải đi qua Hội đồng thẩm định liên Bộ và các nhà khoa học để phản biện, bóc tách thuật toán, đánh giá các tác động định tính về mặt chính trị, lòng dân, và an sinh xã hội – những thứ mà AI không thể số hóa được.Giai đoạn Phê duyệt (Quyết định chính trị): Quyết định bấm nút tối ưu cuối cùng hoàn toàn thuộc về ý chí chính trị của Chính phủ và Quốc hội. Chính phủ có quyền bác bỏ phương án có điểm số GDP cao nhất của AI nếu phương án đó vi phạm các giá trị cốt lõi về chủ quyền quốc gia hoặc làm gia tăng bất bình đẳng xã hội. AI chỉ định hình không gian giải pháp, còn Con người định hình giá trị quốc gia."),
    ],
    12: [
        ("a", "Mô hình AIDEOM-VN tích hợp 6 module có thực sự hỗ trợ ra quyết định tốt hơn so với phân tích rời rạc từng bài không?", "Giá trị cộng thêm của AIDEOM-VN không nằm ở từng thuật toán riêng lẻ (vốn đã giải ở Bài 1–11), mà ở khả năng liên thông dữ liệu: đầu ra dự báo của M1 (Cobb-Douglas) trở thành đầu vào ràng buộc ngân sách cho M3 (tối ưu phân bổ); bản đồ sẵn sàng số của M2 (TOPSIS) định hình hệ số biên β cho M3; còn M4–M5 phản hồi rủi ro lao động và an ninh ngược trở lại để hiệu chỉnh kịch bản. Nhờ đó nhà hoạch định nhìn thấy hệ quả dây chuyền của một quyết định thay vì các mảnh ghép tách rời. Tuy nhiên cần lưu ý sai số tích lũy: mỗi module có giả định riêng, khi nối chuỗi thì sai số nhân lên, nên dashboard phải hiển thị khoảng tin cậy chứ không chỉ một con số điểm."),
        ("b", "Trong 5 kịch bản chính sách (Truyền thống, Số hóa nhanh, AI dẫn dắt, Bao trùm số, Tối ưu cân bằng), kịch bản nào nên được khuyến nghị cho Việt Nam giai đoạn 2026–2030?", "Không có kịch bản nào tối ưu tuyệt đối trên mọi tiêu chí — đây chính là bài học xuyên suốt từ Bài 7 (Pareto). Kịch bản **S5 (Tối ưu cân bằng)** do chính mô hình chạy ra thường là điểm thỏa hiệp hợp lý nhất vì cân đối tăng trưởng, bao trùm vùng miền và rủi ro. Kịch bản **S3 (AI dẫn dắt)** cho GDP cao nhất nhưng khoét sâu chênh lệch vùng và rủi ro an ninh dữ liệu; **S4 (Bao trùm số)** công bằng nhất nhưng hi sinh tốc độ. Khuyến nghị thực tiễn: lấy S5 làm xương sống, lồng ghép front-load nhân lực số (bài học Bài 8 và Bài 10) để tạo 'đệm bảo hiểm' trước các cú sốc."),
        ("c", "AIDEOM-VN có nguy cơ trở thành công cụ 'kỹ trị hóa' (technocracy) chính sách công, làm lu mờ thảo luận dân chủ không? Làm sao để tránh?", "Đây là rủi ro thực và đã được cảnh báo ở Mục 11 của bài báo nguồn: 'AI hỗ trợ ra quyết định, không thay thế trách nhiệm chính trị'. Mọi trọng số (a₁…a₇ ở Bài 3, w ở Bài 6–7, β ở Bài 4) đều là lựa chọn giá trị chứ không phải sự thật khách quan — ai chọn trọng số là người thực sự quyết định chính sách. Để tránh kỹ trị hóa: (1) công khai toàn bộ giả định và trọng số để xã hội phản biện; (2) luôn trình bày dưới dạng menu đánh đổi (Pareto front) thay vì một đáp án duy nhất; (3) áp dụng cơ chế 'human-in-the-loop' — mô hình chỉ định hình không gian giải pháp, còn Quốc hội và Chính phủ định hình giá trị quốc gia."),
    ],
}